### ISSUE TITLE
Use code weaving

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/Zinnia.Unity#210]
This will solve our API accessibility issue when using UnityEvent's inspector to wire things up.

```
if private field X has [Tooltip] attribute 
then create public Property X
if found method ConfigureX
then add ConfigureX to end of Property X.setter
and create OnValidate add ConfigureX to OnValidate
if Property is descendant of `UnityEngine.Object`
then add `ClearX()` method which sets field to `Default(T)`
if Property is a collection
then add `ClearX()` method which calls x.Clear()
If Property is "sub class"
then add `ClearX()` method which sets sub class to `Default("sub class")`
```

`ConfigureX` here can optionally return `T` to change the value we set in the property setter. This allows clamping values for example.

**Comment by thestonefox** [comment]
https://www.thesaurus.com/browse/unfurl

**Comment by thestonefox** [comment]
Manually add

```
/// <summary>
/// My info
/// </summary>
[Unpack]
public Type MyProperty {
  get; set;
}

///Optional confirugation if the property value changes.
protected virtual Type ConfigureMyProperty(Type newValue) {
  // Takes the existing property value and the given new value and does something
  return DoSomething(MyProperty, newValue);
}
```

is converted at compile time to: 

```
/// This shows up in the inspector
[Tooltip("My Info"), SerializeField]
private Type myProperty;

/// <summary>
/// My info
/// </summary>
[Unpack]
public Type MyProperty {
  /// This sets up the public getter
  get { return myProperty;}
  set {
    /// this sets the internal field based on any configuration required on the given value
    /// also allows this to be set by a UnityEvent
    myProperty = ConfigureMyProperty(value);
  }
}

/// If this is an Object/Collection/SubClass
/// Works around the issue with UnityEvents not allowed to set `null` on Objects
public virtual Void ClearMyProperty() {
  // Object -> MyProperty = default(T);
  // Collection -> MyProperty.Clear();
  // SubClass -> MyProperty.fieldA = default(fieldAType), etc
}

protected virtual Type ConfigureMyProperty(Type value) {
  // Takes the existing property value and the given new value and does something
  return DoSomething(MyProperty, newValue);
}

/// Gets created if not found, if is found then gets added to.
protected virtual void OnValidate() {
 /// ensure to use the field as that is the updated value.
 ConfigureMyProperty(myProperty);
}
```

**Comment by bddckr** [comment]
Agreed!

**Comment by thestonefox** [comment]
As previously discussed about the Property and being able to specify the access on get, set

It makes no sense to apply the [Unpack] attribute to anything other than public get/set

If the set is protected then you don't want to be changing the value via the inspector anyway.

And there's little point to a public set but protected get, what's the point on blind setting something without being able to read it.

So I propose that [Unpack] only operates on

`public Type MyProperty;`

**Comment by bddckr** [comment]
That won't work as these attributes are only valid on fields, not properties. Here's an example compile error you get:
>error CS0592: The attribute `UnityEngine.TooltipAttribute' is not valid on this declaration type. It is valid on `field' declarations only

**Comment by thestonefox** [comment]
Tooltip is something we auto generate. But we still need a way of providing other manual attributes to the auto created serialised fields

**Comment by bddckr** [comment]
## WIP report
### "Serialized properties"
```c#
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    public float Test;

    protected virtual void Awake()
    {
        Test = 42.123f;
    }
}
```
is weaved to
```c#
using System.Runtime.CompilerServices;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
  [SerializeField]
  private float test;

  public NewBehaviourScript()
  {
    base..ctor();
  }

  protected virtual void Awake()
  {
    this.Test = 42.123f;
  }

  [CompilerGenerated]
  public float Test
  {
    [CompilerGenerated] get
    {
      return this.test;
    }
    [CompilerGenerated] set
    {
      this.test = value;
    }
  }
}
```
I switched to make the actual code specify public fields here because of a few things:
* All these annotations we're using (Tooltip etc.) only work with fields, not properties and we don't want to reinvent them all.
* It's easy to specify which field should take part in the weaving by just making it PascalCase instead of camelCase.

### `INotifyPropertyChanged` + property changed methods
Note `AddINotifyPropertyChangedInterface` + `OnTestChanged`:
```c#
using PropertyChanged;
using UnityEngine;

[AddINotifyPropertyChangedInterface]
public class NewBehaviourScript : MonoBehaviour
{
    public float Test;

    protected virtual void Awake()
    {
        Test = 42.123f;
    }

    protected virtual void OnTestChanged(object before, object after)
    {
        Debug.Log($"{nameof(Test)}: {before} -> {after}");
    }
}
```
is weaved to
```c#
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Threading;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour, INotifyPropertyChanged
{
  [SerializeField]
  private float test;
  [NonSerialized]
  private PropertyChangedEventHandler PropertyChanged;

  public NewBehaviourScript()
  {
    base..ctor();
  }

  protected virtual void Awake()
  {
    this.Test = 42.123f;
  }

  protected virtual void OnTestChanged(object before, object after)
  {
    Debug.Log((object) string.Format("{0}: {1} -> {2}", (object) "Test", before, after));
  }

  [CompilerGenerated]
  public float Test
  {
    [CompilerGenerated] get
    {
      return this.test;
    }
    [CompilerGenerated] set
    {
      if (this.test == value)
        return;
      object test1 = (object) this.Test;
      this.test = value;
      object test2 = (object) this.Test;
      this.OnTestChanged(test1, test2);
      this.<>OnPropertyChanged(<>PropertyChangedEventArgs.Test);
    }
  }

  public event PropertyChangedEventHandler PropertyChanged
  {
    add
    {
      PropertyChangedEventHandler changedEventHandler = this.PropertyChanged;
      PropertyChangedEventHandler comparand;
      do
      {
        comparand = changedEventHandler;
        changedEventHandler = Interlocked.CompareExchange<PropertyChangedEventHandler>(ref this.PropertyChanged, (PropertyChangedEventHandler) Delegate.Combine((Delegate) comparand, (Delegate) value), comparand);
      }
      while (changedEventHandler != comparand);
    }
    remove
    {
      PropertyChangedEventHandler changedEventHandler = this.PropertyChanged;
      PropertyChangedEventHandler comparand;
      do
      {
        comparand = changedEventHandler;
        changedEventHandler = Interlocked.CompareExchange<PropertyChangedEventHandler>(ref this.PropertyChanged, (PropertyChangedEventHandler) Delegate.Remove((Delegate) comparand, (Delegate) value), comparand);
      }
      while (changedEventHandler != comparand);
    }
  }

  protected void <>OnPropertyChanged(PropertyChangedEventArgs eventArgs)
  {
    PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
    if (propertyChanged == null)
      return;
    propertyChanged((object) this, eventArgs);
  }
}
```

## To Do
While the above is pretty much already solving the Unity problem of properties not being serializable there still some remaining work:
* `On<PropertyName>Changed` methods should be allowed to take the specific type (float in the example), instead of `object`.
* Add `OnValidate` method that calls the same things the setter implementations call. I.e. for each field that has a matching property now, get the setter method, remove the equality check therein and copy the remaining IL instructions of that setter into `OnValidate`.
* Add `Clear<PropertyName>` methods for each field/property that uses or inherits from `UnityEngine.Object`.
* Take the field's XML documentation and automatically add the `[Tooltip]` annotation to the field. Look into copying the same XML documentation from the field to the field to the auto-generated property. Also look into making this a standalone addin to allow us to only write docs once (as XML docs). _XML documentation isn't part of the IL - find another way to do this just for the purpose of adding the tooltip/ensure our auto-generated docs get the property docs right._

Since we're only shipping build .exe + .dlls to make it work in our Core repo we additionally need to look into forking/creating a new repo to get the standalone Fody executable, the used addin forks as well as our newly created addins into a maintainable state.

**Comment by thestonefox** [comment]
So does this mean

```
[Tooltip("My Field"), SerializeField, MinMaxRange(0f, 1f), InternalSetting]
public FloatRange MyRange = new FloatRange(0f, 1f);
```

Would get all converted as expected and display the tooltip in Unity?

Do you have access rights to create new git repos on the ExtendReality organisation? If not, I'll set it up so you can create the relevant repos.

**Comment by bddckr** [comment]
Yup it does (ignore me just testing with `float` and `Range` instead here, I'm not yet working with Core in this test project):
![image](https://user-images.githubusercontent.com/294347/48676324-76134a00-eb65-11e8-9e45-c7c2ffc79877.png)

I have the necessary rights - nothing to do there!

**Comment by thestonefox** [comment]
Had a thought, we need to support setting enums via UnityEvents too. But UnityEvents don't let you select enum values.

So what if we detect an `enum` type and create a method (as well as the public property)

```
public virtual void SetMyPropertyName(int value) {
  //set enum here
}
```

This int value could potentially even be used as the bitmask if you wanted to set multiple values on an enum. So perhaps we'd need to know if the enum was a single or multi value enum to decide what to do in the setter.

**Comment by bddckr** [comment]
Hmm. I'd love to support things like that (and vectors!) that aren't supported by Unity as constants there.

Such a method doesn't help us, though? Users don't really know the enum values in advance and for bitfields it would be even harder for them.

Besides us having to support all backing types:
>The approved types for an enum are byte, sbyte, short, ushort, int, uint, long, or ulong.

**Comment by thestonefox** [comment]
I just remembered. We need to make sure anything that extends `UnityEngine.Object` needs to get a `ClearMyProperty()` method that sets it to null because you can't clear then via the UnityEvent otherwise.

**Comment by bddckr** [comment]
### Progress report

Got it all working now. For (`public`, non-`static`) fields marked with the attribute you get:
1. The field is changed to `private` + `[SerializeField]`.
1. A property is added that is public (`get` + `set`).
    1. The field's name is left as is to prevent potential compilation issues resulting in a loss of serialized data. The property name just switches the case of the first character of the field name: `fieldName` creates `PropertyName` and `FieldName` creates `propertyName`.
1. If a `void Set<FieldName>(T, T)` method exists then that will be called in the property's `set`.
    1. The method name check is case _insensitive_.
    1. The method can have any accessibility level.
1. Any usage of the field is changed to use the property's `get` or `set` instead.
    1. Field assignments in the declaring type's constructor are ignored since that would give issues because the type isn't yet fully initialized (the constructor needs to run first).
1. A method `void OnValidate()` is added to the declaring type.
    1. In case the superclass/subclass implements the method already any necessary changes are done so each subclass calls the superclass' implementation first. This includes automatically changing accessibility level and adding `virtual` + `override`.
    1. In case the method already exists we add our injected code _after_ the existing instructions in the method's body. We also _don't_ do the superclass/subclass changes above in this case.
1. If the field's type is inheriting from `UnityEngine.Object` a method `public void Clear<FieldName>` is added. This method sets the _property_ to `null`.

### Remaining To Dos

1. Most steps above are independent and therefore should be implemented independently and result in a standalone assembly to make life easier. Decide on whether this is something we want to do and when.
1. Find a good name for the attribute(s, see point directly above).
1. Improve point 5.i. above so it's always just making hierarchies work and document that we assume this is what the user wants.
1. Look into merging the assemblies again after Unity didn't like it anymore.

**Comment by bddckr** [comment]
All done except for the assembly merging which probably won't happen as Fody and Unity don't like it much. No problem really, just means we're shipping multiple `.dll`s.

Some good improvement ideas:
* Type has a `public Clear()` method -> Call that method
* Type is a reference type -> Set to `null` (which is `default(T)`
* Type is a value type -> Set to `default(T)` (which is just `new T()`)
If the method already exists we don't generate it, that way you can "override" it.

**Comment by bddckr** [comment]
This is now resolved thanks to our creation of [Malimbe](https://github.com/ExtendRealityLtd/Malimbe) and merging #332.
