### ISSUE TITLE
Offer events for "user presence" changes

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/Zinnia.Unity#252]
Unity's XR support has this but we should probably also offer SDK repo specific implementations.

Additionally perhaps a "user _moved_ in the last N seconds" component is useful in this case.

**Comment by fight4dream** [comment]
This is available as a pattern matching
[Runtime/Pattern/XRDevicePatternMatcher.cs](https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/553/commits/219d1eb52b39f7e0111fae14c0366e9fae1cad1e#diff-cc8b0b247cb5beae0909654becf5d9d7d4f0e3cd40af256cbe8bf4384711be6c)
219d1eb
#553
