### ISSUE TITLE
Allow for GameObject as Target in Obscurance Query

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Zinnia.Unity#264]
The ObscuranceQuery currently requires a Collider as the target, however this is limiting when using objects that contain compound colliders.

A better idea would be to provide a GameObject as the target and use that as the overall collision check.

```c#
bool isObscured = raycastHits.Any(hit =>
{
    GameObject hitGameObject = hit.transform.gameObject;
    return hitGameObject != source && hitGameObject != target;
});
```

**Comment by bddckr** [comment]
It may also be a good idea to throw an exception (and then disable the script to prevent throwing that over and over?) in case the `target` doesn't have any `Rigidbody`, nor `Collider` on it.
