### ISSUE TITLE
Turn all fields into properties

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/Zinnia.Unity#269]
Pros
• Encapsulation is better
• No breaking change if there needs something to be done in the get or set but was just a dumb property with a backing field so far
• Shows up in the UnityEvent inspector
• Accessibility can be defined for get vs set

Cons
• More to type: You have to add `{ get; set; }` at all times, additional `[Serialized, Validated]` from Malimbe for serialized properties

Visual Studio has a template to create a property: `prop` (and `propg`, too? That one may be ReSharper only).

**Comment by thestonefox** [comment]
We're done with this too after https://github.com/ExtendRealityLtd/Zinnia.Unity/tree/feat/reactivity is merged right?

**Comment by bddckr** [comment]
Resolved by #332.
