### ISSUE TITLE
Fix inconsistent naming of private members

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/Zinnia.Unity#270]
Should fields be prefixed by `_` or just be camelCase?

**Comment by thestonefox** [comment]
the `_` gives us just an extra choice of naming. But i'm not fussed if we drop it

**Comment by thestonefox** [comment]
it does denote however that this field probably has a facing Property

**Comment by thestonefox** [comment]
Looking over the code, it doesn't look like we use `_` to prefix any private fields anymore (except `_interface` in the InterfaceContainer but I think this is appropraite)
