### ISSUE TITLE
CalledBySetter usages should be wrapped in Application.isPlaying checks where necessary

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/Zinnia.Unity#300]

**Comment by thestonefox** [comment]
This is done in latest malimbe right?

**Comment by bddckr** [comment]
Resolved by https://github.com/ExtendRealityLtd/Malimbe/commit/173a358bcd6d39e4f2a45bb9eabcd65090e6a89a which was merged in with 653f213fc5bbd57e5afac8f89703f240ab3cd4b0.
