### ISSUE TITLE
Add a "SuperCollection"

### ISSUE THREAD

**Issue by bddckr** [ExtendRealityLtd/Zinnia.Unity#303]
The idea here is to have one collection type to use everywhere.

It should come with events:
* ElementAdded
* ElementRemoved
* BecamePopulated
* BecameEmpty

A readonly view for code purposes helps to enumerate the collection while enforcing to call the methods to mutate:
* Add
* Remove
* Clear

Instead of offering a subclass that does uniquing we offer more methods:
* AddIfNew
* RemoveAll

This collection should be ordered and as such more methods are to be offered:
* Add/RemoveAt(int index)
* AddToStart/RemoveFromStart
* AddToEnd/RemoveFromEnd

Additional methods and a field `int index` help with UnityEvent usage (as their inspector only allows calling methods with a single argument/no constants).

**Comment by thestonefox** [comment]
We have this now right with the feat/reactivity branch?

Other than EventStack still being different (but i think it still should be different imho)

**Comment by bddckr** [comment]
Resolved by #332.
