### ISSUE TITLE
ObjectPointer should have a configurable LayerMask for the raycast 

### ISSUE THREAD

**Issue by skahlert** [ExtendRealityLtd/Zinnia.Unity#398]
### Expected behavior

The ObjectPointers should be able to configure the layers the raycast ignores. While the validity allows to invalidate a raycast depending on configuration, it does not allow the raycast to penetrate certain colliders.
Simple example:
I want my teleportation collider not to interact with a menu, while my straight pointer should.

### Current behavior

Cuttently the raycast is hardcoded to the IgnoreRaycast layer, which is not flexible enough for some applications.

**Comment by thestonefox** [comment]
the ObjectPointer doesn't do any raycasting.

The `PointsCast` does the casting and it has an option to provide a custom PhysicsCast object which allows you to specify Layers To Ignore.
