### ISSUE TITLE
CameraColorOverlay - Event on AddColorOverlay ended

### ISSUE THREAD

**Issue by Adiwan** [ExtendRealityLtd/Zinnia.Unity#406]
I'd like to have an event whenever the color has been completely faded in and out.

Background: I'm writing on a scene changer and wanted to start loading the new scene when it fully transitioned to black (or the fully opaque overlay color).

Workaround:
I need to listen to the "Removed" UnityEvent and use the Blink method.
It seems very counter-intuitive to use it this way.

If you're at it please make a public AddColorOverlay method with color and duration parameters.

**Comment by thestonefox** [comment]
There already is an event when a colour is added, it's called `Added` it is emitted when the colour reaches the target colour overlay.

You can simply do something like:

```
fader.OverlayColor = Color.black
fader.AddDuration = 1f
fader.AddColorOverlay();
```

Then have an event on the `Added` event that does the scene load.

**Comment by Adiwan** [comment]
I used the Added event but it is invoked immediately when the overlay has been added. I want an event when the color transition has finished.

**Comment by thestonefox** [comment]
How about this for a solution?

https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/407

You now get an AddTransitioned event and a RemoveTransitioned event

**Comment by Adiwan** [comment]
I'm happier now! I can now make my code a little bit cleaner than before and it will become a little bit more readable.

That can also benefit for easier scripted (as in storyboard scripted) teleportation and make the location change occur when a longer fade to black has completed, which won't startle the user as much as the fade to black were instant or the location change were at the start of the fade.
