### ISSUE TITLE
Teleport snap to floor incorrect

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Zinnia.Unity#411]
Thanks @mattdavisgames . I dig further into the 'Comparer' used.
It is `SurfaceLocator.RayCastHitComparer` and its compare function is `return (int)(x.distance - y.distance);`
I think this is incorrect and should be `return x.distance.CompareTo(y.distance)`

Update:
confirmed that after changing the comparer function, the example scene house veranda/foundation can be reached correctly

_Originally posted by @fight4dream in https://github.com/ExtendRealityLtd/VRTK/issues/2042#issuecomment-509975640_

**Comment by thestonefox** [comment]
Good find
