### ISSUE TITLE
CollisionTracker 'Stop Collisions On Disable' does not work for trigger collider

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Zinnia.Unity#421]
### Environment

* Version of Zinnia (7a8f5aa)
* Version of the Unity software (2019.2.0f1)

### Setup

1. Create a Cube. It has BoxCollider.
2. Create a Sphere. It has SphereCollider. Make its IsTrigger=true. Add rigidbody onto it, check IsKinematic=true.
3. Add CollisionTracker to Sphere, EmittedTypes=Trigger only. StatesToProcess=Enter and Exit. StopCollisionsOnDisable=true.
4. Create a empty game object named “Touch”, add CollisionNotifierEventProxyEmitter.
5. Create a empty game object named “Untouch”, add CollisionNotifierEventProxyEmitter.
6. Create a Capsule. Disable the capsule game object.
7. Wire up the Sphere’s CollisionTracker to Touch and Untouch proxies.
8. Wire up the Touch and Untouch proxies to (Capsule) GameObject.SetActive(true/false)

### Steps to reproduce

1. touch the Cube with the Sphere, this should make Capsule appears.
2. untouch the Cube/Sphere, this should make Capsule disappears.
3. touch the Cube with the Sphere again, Capsule appears as expected, then Disable the Sphere game object.

### Expected behavior

Capsule should disappears.

### Current behavior

Capsule is not disappeared.

![image](https://user-images.githubusercontent.com/22952143/63971228-9f8bd980-cad8-11e9-8420-8924e6c9a505.png)

if CollisionTracker is on a trigger collider, CollisionTracker.StopCollision() will generate a payload with IsTrigger=Cube.isTrigger. In this case regardless to the fact that our own collider is a trigger and the 'collision' is indeed a trigger exit.

**Comment by thestonefox** [comment]
Ok so it seems if you set the `Emitted Types` to `Everything` then it works as expected. So it's something to do with the emitted type being set as `Trigger` i think

**Comment by thestonefox** [comment]
Yeah ok so I think this makes sense now.

The issue is:

The Cube is not a trigger collider, and what happens is on StopCollision it checks to see if it can emit.

Well the `data.IsTrigger` is false because the thing (cube) colliding with the sphere is not a trigger collider, and therefore it can only emit on types of Collision.

The emitted types will say "you can emit when you collide with a collider or a trigger" and in this instance the trigger is colliding with a collider and not another trigger.

I _think_ this is how it's supposed to work, not sure if @bddckr can chime in as he originally wrote it so may expect it to work this way.

**Comment by thestonefox** [comment]
In short, i think you basically want your `Emitted Types` set to `Everything` which I _think_ is saying emit the event whether I'm colliding with a collider and/or a trigger collider.

Setting it to `Trigger` means only emit when I'm colliding with another trigger collider (_i think_)

**Comment by bddckr** [comment]
Yeah that's what the thought was behind this. I wonder if there's a point in opening this up a bit (a second setting perhaps?), though - I can see changing the emitted types being a bigger behavioural change, depending on the intended use. Though one can probably work around that by having two collision trackers?

**Comment by fight4dream** [comment]
My usage is that the trigger is usually something active/moving while the collider is static/structural.
I don’t need to track collision, nor to push around with the trigger object. 

I intuitively thought that the emit type correspond to OnCollisionEnter and OnTriggerEnter (and stay/exit). 

It is indeed the case, but due to Unity not providing the “source” collider (to easily check whether the pair is collision or trigger)  , the best we can do is to record whether we have entered through OnCollision or OnTrigger and then emit the correct payload on disabled
