### ISSUE TITLE
Ability to provide start value for Action (was/BooleanAction with DefaultValue=true is not activated if its source is not activated initially)

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Zinnia.Unity#422]
1. Create a BooleanAction “A”
2. Create a BooleanAction “NotA” with DefaultValue=true
3. Link “A” as a source of “NotA”
4. Play scene

“NotA” default value makes it work like a “negateAction”. Using debug inspector mode, i can see that DefaultValue=Value=true. But IsActivated=false. 

When “A” is set true & activated, “NotA” Receive(true), set value to false, but compare with DefaultValue it ShouldActivate() is false. It should fire Deactivated but because it initially is not activated, the event is not fired. 

Expected “A” to be activated at first but it is not.

My more elaborate use case is:
PlayerIsDead booleanAction
HasTime booleanAction
PlayerIsAlive=!PlayerIsDead
GamePlaying=All(PlayerIsAlive, HasTime)

GamePlaying is not activated at first (Activated also not called) and if PlayerIsDead set to true, GamePlaying deactivated is also not called

**Comment by bddckr** [comment]
This seems to be a result of the design decision to not actually activate/deactivate on startup. I believe we noticed that's never needed because `Value` will be `defaultValue` (we set that, as it's the only thing that makes sense until runtime start) at startup.

Just seems like an oversight of the later addition of `sources` not working with this - the sources seem like they do need to be checked on startup (at the end of the current `Awake` implementation?).

I'll leave it up to @thestonefox to confirm or deny that theory 😄

**Comment by thestonefox** [comment]
I'm still a bit confused over this.

If NotA is true by default, then A is set to true, the NotA receives `true` right?

But that is just telling NotA you're already in this state so don't do anything.

NotA is true by default, so passing `true` to it doesn't change anything, which is correct, no?

**Comment by bddckr** [comment]
Hmm. You're right!

The negating functionality of a BooleanAction is applying to the values it receives:

| Received value | Activation State |
|----------------|------------------|
| `true`         | Deactivated      |
| `false`        | Activated        |

As such I believe this issue boils down to just the following:
The setup as explained in the first message results in the "negated" BooleanAction to **not** be activated, while it should, if one assumes that going from design time to runtime should forward the current value from sources to the connected Actions.

I believe that was ultimately a design decision: We shouldn't assume "kicking things off" at startup is expected for Actions, as Actions are primarily **change driven**. I.e. don't create a change on behalf of the user on startup.

---

Having said that I believe in this case calling `EmitActivationState` on the connected source (`A` in the first message here) is all it takes to handle the explained use case.

@fight4dream can you check that assumption?

**Comment by fight4dream** [comment]
Calling `EmitActivationState()` on “A” will make “NotA” activates and fires Activated

**Comment by bddckr** [comment]
Eh yeah I'm dumb (and currently 🤒).

Your issue stems from the fact that NotA won't trigger when A is true. It needs to be false. If it's false then it still won't trigger at runtime - that's why you need `EmitActivationState` to do so.

**Comment by thestonefox** [comment]
Concept of a new `StartValue` property, which is set only once when the Action is initially created.

it would be set in the `Start()` method of the Action and simply call `Receive(StartValue)`

**Comment by extendreality** [comment]
Fixed in https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/507
