### ISSUE TITLE
Support for SRP breaks compatibility with Unity 2018

### ISSUE THREAD

**Issue by mattdavisgames** [ExtendRealityLtd/Zinnia.Unity#424]
Importing Zinnia to Unity versions below 2019 (I'm using 2018.4.5f1) causes the following compile error:

`Assets\Zinnia.Unity\Runtime\Process\Moment\MomentProcessor.cs(93,53): error CS0246: The type or namespace name 'ScriptableRenderContext' could not be found (are you missing a using directive or an assembly reference?)`

I believe ScriptableRenderContext and RenderPipelineManager were only introduced in Unity 2019.

**Comment by thestonefox** [comment]
They were actually in 2018.4 but in the Unity.Experimental.Rendering namespace. However, I don't think it's worth supporting experimental namespaces so I'll make it so it's 2019.1 only and SRP just won't work in 2018 (using a script define to remove the compile error)

**Comment by thestonefox** [comment]
PR with fix https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/425
