### ISSUE TITLE
Make compatible with the Unity Package Manager and remove hard dependencies

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Zinnia.Unity#430]
At the moment, Zinnia is included with other projects as a sub domain, or hard copied into the project.

Adding a `package.json` to the root of the repo with the relevant contents will allow it to become a Unity Package.

This also means that the dependency of Malimbe should be hard removed from Zinnia and referenced as a dependency in the `package.json`

To ensure the package is available to Unity projects via UPM it will also need to be pushed to a registry like npmjs

This should all be automated via a CI+CD pipeline (as like with Malimbe).

**Comment by bddckr** [comment]
I'll try to do this over the weekend.

Of interest:

https://github.com/ExtendRealityLtd/Malimbe/blob/9cf1ed090fc33ef1e64de3ade406b1f1f21942c1/package.json#L25-L33

https://github.com/ExtendRealityLtd/Malimbe/blob/9cf1ed090fc33ef1e64de3ade406b1f1f21942c1/.devops/azure-pipelines.yml#L14

https://github.com/ExtendRealityLtd/DevOps

**Comment by thestonefox** [comment]
actually when this change is done and Malimbe is removed as a hard dependency from the Zinnia package, it will initially break VRTK as we'd no longer recommend people use Git submodules to pull down dependencies and if the project containing VRTK didn't have zinnia in it's manifest then it wouldn't pull down the Malimbe dependency either.

I can raise a ticket in VRTK to prepare VRTK for also becoming a package that depends on zinnia and provides new instructions of how to add VRTK to a project by updating the project manifest.

VRTK should then still work even though all the prefabs are bundled in there, but we can start separating them out bit at a time when the 3 dependencies are nested.

**Comment by fight4dream** [comment]
If i have a custom branch/fork from vrtk&zinnia, what changes or how would I use my custom branch when it becomes the package?

Btw 2019+ will auto upgrade the malimbe dlls, will this upm integration solve that problem?

**Comment by thestonefox** [comment]
how is Unity auto upgrading dlls? they're compiled?

The differences will be VRTK will no longer submodule zinnia, instead it will pull it in via UPM

and Zinnia will pull in Malimbe via UPM as well. I don't see how it would affect custom branches/forks

**Comment by bddckr** [comment]
Your project manifest can override any package. All the things apply that UPM supports: Pointing to a different version, a git URL or a local folder. I'd suggest the local folder for forks and contribution work.

**Comment by fight4dream** [comment]
Yes they are recompiled

**Comment by bddckr** [comment]
Open an issue with details please. There's a lot of things that could be: Malimbe running as part of the compile chain itself (it does some code weaving after all!), Unity doing an API updater run on the .dll (which we can prevent I believe) etc.

**Comment by fight4dream** [comment]
https://github.com/ExtendRealityLtd/Malimbe/issues/48

sorry it's not the dll, it's their metas
