### ISSUE TITLE
Attribute to allow changing the inspector text for a parameter

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Zinnia.Unity#431]
Unity by default will convert a field/property based on its casing into separated words uppercasing the first letter:

`myParamIsThis` becomes `My Param Is This`

But if there is something that is an acronym like

`mySqlQuery` then it becomes `My Sql Query` which really should read `My SQL Query`

Here is a potential solution for such an attribute:

https://answers.unity.com/questions/1487864/change-a-variable-name-only-on-the-inspector.html

**Comment by extendreality** [comment]
PR https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/434
