### ISSUE TITLE
error for Can't save an immutable Prefab

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Zinnia.Unity#440]
### Environment

* Version of Malimbe (44dd7bc)
* Version of the Unity software (Unity 2018+)

### Steps to reproduce

1. Clone VRTK project, Malimbe is included as package
2. Click on any prefabs that would use Malimbe's custom inspector

### Expected behavior

There should not be mark dirty/re-serialize anything if no actual attempt to change value manually.

### Current behavior

Argument Exception: Can't save an immutable Prefab
![image](https://user-images.githubusercontent.com/22952143/67156114-0f864580-f34d-11e9-8ff3-41627ca9000b.png)

### PS

It also mark dirty/re-serialize a non-prefab (instanced object) whenever we just select and inspect it.

**Comment by bddckr** [comment]
Thanks for the report!
