### ISSUE TITLE
String Identifier Rule

### ISSUE THREAD

**Issue by RunenGamer** [ExtendRealityLtd/Zinnia.Unity#454]
### Environment

    Source of VRTK: Github
    Version of VRTK: release/3.3.0-alpha (e43089a)
    Version of Unity3D (e.g. Unity 2017.3.0f3)
    Hardware used (e.g. Vive)
    SDK used (e.g. SteamVR)

### Steps to reproduce

1. Open "041_Controller_ObjectSnappingToDropZones"
2. See that that "Valid Object List Policy" only supports Tags, Layers and Scripts
3. The scene uses tags to identify correct objects
4. In my game, i got > 100 snap drop zones/objects. Therefore I would need >100 different Tags/Layers/Scripts. 

### Expected behavior

I propose a forth Option for VRTK_PolicyList: "String Identifier"

If you chose VRTK_PolicyList.CheckType = "String Identifier"
Then VRTK_PolicyList.TypeCheck would check if the GameObject obj got an Script VRTK_PolicyListStringIdentifier. If so, it checks whether the string specified in VRTK_PolicyListStringIdentifier matches one identifier of VRTK_PolicyList.

Basically it's the same system like tags, but it don't mess up a projects tag-structure.

If you like it, I can start an PR immeadiatly, because I already programmed this change.

**Comment by bddckr** [comment]
Is the intend to just have a known component this rule would look up? E.g. `StringIdentifier` which is just a component that gives a `string` you can set in the inspector?

If so: All we should then offer is one string on the identifier side and a single `RegexRule` IMO.

**Comment by bddckr** [comment]
@thestonefox Is the intend to just have a known component this rule would look up? E.g. `StringIdentifier` which is just a component that gives a `string` you can set in the inspector?

If so: All we should then offer is one string on the identifier side and a single `RegexRule` IMO.

**Comment by thestonefox** [comment]
I don't even remember what the original feature was.

I think it was you would have a component that you would apply to the thing you wanted the rule on, and in that component was a single string which you could put extra definitions onto.

I've not come across a use case as of yet for implementing this.

**Comment by bddckr** [comment]
In v4 either a ListContainsRule or a TagRule could be used, but both aren't giving the weak coupling the original request was about:

With a single string being on a ton of objects one could easily identify objects during a Rule check.

In general I don't like stringly typed APIs and thus would instead recommend any user who has this need creates their own
1. enum of values they will use and
2. component that holds that enum value and
3. Rule subclass that just looks for that new component and checks the enum for the Rule's own enum value.

**Comment by thestonefox** [comment]
We have this now with the 
https://github.com/ExtendRealityLtd/Zinnia.Unity/blob/master/Runtime/Rule/StringInListRule.cs
