### ISSUE TITLE
Thresholding float to boolean

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Zinnia.Unity#463]
## Is your feature request related to a problem?

The current FloatToBoolean can only do “thresholding” if the input is within [-1,1]. It cannot be used for high values such as Speed or Distance. 

## Describe alternatives you've considered

1. Remove the “Range attribute/display” from the bound; or

2. Have another unbounded range and add an option to select which one to use; or

3. rename the current one as NormalizedFloatToBoolean and create another unbounded FloatToBoolean; or

4. Create another UnboundedFloatToBoolean

**Comment by thestonefox** [comment]
The float is supposed to be normalized which is why it is in the range of -1 to 1

Consider normalizing your float before passing it to the transformer

otherwise having a -Infinity, Infinity range is unwieldy

**Comment by fight4dream** [comment]
I'm interested in use cases such as 
detect two object's distance within the range (0, 30m) or far away (30m, +inf)
detect the speed of an object slower (0, 30m/s) or faster (30m/s, +inf)

in these case, we will have to pass through a remapper which maps from a range (0, 30*2)
and then float to bool detect lower or higher than 0.5
![image](https://user-images.githubusercontent.com/22952143/67901026-b5814d80-fba0-11e9-9015-1740dd72abdd.png)

I agree that option 1, 2 is unhandy. 
option 3 may be confusing for existing user
option 4 could be the reasonable choice

**Comment by thestonefox** [comment]
I think we should just remove the `MinMaxRange(-1f, 1f)`

and provide a `Float Normalizer` class

**Comment by fight4dream** [comment]
I think the Float Range Value Remapper (with the output range of (-1,1) or (0,1)) is the Float Normalizer

**Comment by thestonefox** [comment]
Float Range Value Remapper could just be

FloatToNormalizedFloat and NormalizedFloatToFloat:

```
FloatToNormalizedFloat

Range[0f, 10f] -> 5f = 0.5f
Range[0f, 10f] -> 11f = 1f
Range[0f, 10f] -> -5f = 0f
```

```
NormalizedFloatToFloat

Range[0f, 10f] -> 0.5f = 5f
Range[0f, 10f] -> 1f = 10f
Range[1f, 10f] -> 0f = 1f
```

This way they are still both conversion types (float <--> normalizedfloat)

**Comment by extendreality** [comment]
https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/499/commits/b65cd031ba829243d3c3800474f36635e0f5c667

**Comment by thestonefox** [comment]
This is resolved now by removing the min max range on the positive bounds. It isn't required and won't break anything to remove it.
