### ISSUE TITLE
Want a way for Vector3 to magnitude 

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Zinnia.Unity#467]
### Situation

my current project requires detecting speed over threshold a lot.
The data flow is
CollisionTracker enter -> CollisionNotifierProxyEmitter emit (Check ColliderSource valid rule) -> VelocityEmitter emit -> [Vector3 to float (by magnitude)] -> FloatRangeValueRemapper (map to 0,1) -> FloatToBoolean -> Activated/Deactivated
The missing link is Vector3 to float (by magnitude).
As a reference, Vector2ToFloat is extracting components (x or y).

### Suggestion

1. Add Vector3ToFloat, it can extract (by x, y, z or magnitude)
2. Retro add extract (by magnitude) to Vector2ToFloat
3. (optional) ObjectDistanceComparator can be refactored to not have the threshold functionality, rather the data flow can be
ObjectDistanceComparator Process -> ObjectDistanceComparatorEventDataExtractor .DistanceExtracted -> FloatRangeValueRemapper (map to 0,1) -> FloatToBoolean -> Activated/Deactivated

### Alternative suggestion

1. Retro add VelocityEmitter EmitSpeed() and EmitAngularSpeed() and the corresponding float events (just like the ObjectDistanceComparator does emit both a Vector3 and its magnitude)
then the data flow is
CollisionTracker enter -> CollisionNotifierProxyEmitter emit (Check ColliderSource valid rule) -> VelocityEmitter emit speed -> FloatRangeValueRemapper (map to 0,1) -> FloatToBoolean -> Activated/Deactivated

**Comment by thestonefox** [comment]
I'm ok with the `Vector3ToFloat` with additional extraction floats (and retro added to Vector2ToFloat as well).

But i'd add for all the properties:

* magnitude
* normalized
* sqrMagnitude

The property name `Coordinate` doesn't mean all that much then, it should be `Property To Extract` but this would be a breaking change and break a bunch of things so i'm not fussed if it's left as `Coordinate to Extract`

**Comment by thestonefox** [comment]
Also, I don't mind the `VelocityEmitter` emitting the speed as well as velocity.

**Comment by fight4dream** [comment]
VelocityEmitter is in Tracking namespace,
Vector2/3ToFloat is in Data namespace,
feat(Tracking) or feat(Data) shall be used for the PR commit title?

**Comment by thestonefox** [comment]
The can be in 2 separate commits, therefore have 2 different commit titles

and the PR title doesn't really matter, it's not used for anything really

**Comment by fight4dream** [comment]
for Vector[2/3]ToFloat
magnitude and sqrMagnitude are okay they are float.
normalized is not.

**Comment by fight4dream** [comment]
two commits in one PR, or two PR?
it would be hard to squash to maintain separate commits

**Comment by thestonefox** [comment]
Yeah don't bother with normalized.

two commits in 1 PR

**Comment by fight4dream** [comment]
there is a Vector3MagnitudeSetter to do input.normalized * Multiplier
when multiplier =1, it is basically extracting normalized.
should I add one for Vector2MagnitudeSetter? it is in Data namespace as well
