### ISSUE TITLE
SnapZone does not complete snapping if gameObject to snap already has the correct transform settings

### ISSUE THREAD

**Issue by hawkwood** [ExtendRealityLtd/Zinnia.Unity#489]
This is because ApplyPropertiesToInteractable’s TransformPropertyApplier's ProcessTransform() returns without emitting if the target and source transforms are in alignment.  This is an edge case for general usage, but if one programmatically calls snapZoneFacade.Snap(gameObject), on a gameObject that is already aligned, it's much easier to run in to this issue.  Without fully snapping, game objects will not follow a moving snap zone even though it thinks it's snapped.

### Environment

* Code source: Package manager
* Code version: VRTK Prefabs 1.1.8
* Platform version: Unity 2019.2.17
* 3rd party dependencies: N/A

### Steps to reproduce

In editor, run Farm scene using Simulated Camera Rig.
Go to the tools and place the saw in it's snap zone.
Set AvatarObjects transform to pos: -27, 1.5, 9.5; rot: 0, -180, 0
Set RightController transform to pos: 0.3264, 0.1298, 1.0055; rot: 90, 90, 0
In hierarchy, expand the SawSnapZone/Internal/SnappedActions/SnappedObjectFollowsZone/ObjectFollower/Internal and select MomentProcessor.
The component MomentProcessor should be enabled.
Click to grab saw, see MomentProcessor is disabled; release to snap saw, MomentProcessor is still disabled, but it should be enabled.

### Expected behavior

ApplyPropertiesToInteractable’s TransformPropertyApplier should have still emitted it's AfterTransformUpdated events, even though the transform did not move. 

### Current behavior

Since the target and source are close enough, the ProcessTransform returns without emitting, thus not fully completing the snap.

**Comment by WeaselKing** [comment]
I'll add to this with a different case that seems to be affected by the same issue. When teleporting via a call to the facade, a very similar behavior is exhibited to hawkwood's reported issue. 

Sending Teleport(<transformdata>) will work once, but if you send the same transform data, nothing happens. Essentially it should, because the offset data (the headset position) has changed, so we should permit the teleport again. 

My use case in this is to recenter the user and have him/her face in a specific direction. 

You can reproduce this behavior like this:

`



    public class ArbitraryTeleport : MonoBehaviour
    {
        public TeleporterFacade teleportFacadeScript; //Linked to a teleport.instant or teleport.dash.
        public Transform properOrientation; //Where we would like to teleport the user to.
        public Transform deviatedOrientation; //A transform we can slightly manipulate for the purpose of the test.

        private void Update()
        {
            if (Input.GetKeyDown(KeyCode.L))
            {
                PerformRecenter();
            }
            if (Input.GetKeyDown(KeyCode.M))
            {
                PerformDeviatedRecenter();
            }
        }

        public void PerformRecenter() //This works once and only once.
        {
            TransformData teleportDestination = new TransformData(properOrientation);
            teleportFacadeScript.Teleport(teleportDestination);
        }
        public void PerformDeviatedRecenter() //This always works, and is nearly identical but has a very tiny deviation on position
        {
            deviatedOrientation = properOrientation;
            deviatedOrientation.position = new Vector3(deviatedOrientation.position.x + Random.Range(-.001f, .001f), deviatedOrientation.position.y, deviatedOrientation.position.z + Random.Range(-.001f, .001f));
            TransformData teleportDestination = new TransformData(deviatedOrientation);
            teleportFacadeScript.Teleport(teleportDestination);
        }
    }
}`

**Comment by thestonefox** [comment]
I've had a similar issue with the SurfaceLocator only operating if the previous and current points are not equal. So, I'm adding an additional option that allows this equality check to be ignored. I think this same concept could be applied to the TransformPropertyApplier.

Right now you can change the equality tolerance but even setting it to 0 can consider the properties to be equal preventing the logic occurring. So maybe an option that allows you to ignore this equality check can fix this issue too.

**Comment by thestonefox** [comment]
PR that adds the option to ignore equality checking: https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/497
