### ISSUE TITLE
io.extendreality.zinnia.unity problem. Please help !!!

### ISSUE THREAD

**Issue by castana1962** [ExtendRealityLtd/Zinnia.Unity#496]
Hi
I opened an Unity project with the version that it was build but I get an error and I cannot see the scripts into the game objects
This one is the following
DirectoryNotFoundException: Could not find a part of the path "C:\Users\my name\Desktop\........\Library\PackageCache\io.extendreality.zinnia.unity@1.6.0\Dependencies\Supyrb\Editor\Supyrb.Editor.asmdef".
For it Could you helpme to fix it?
Thanks for your time
Alejandro

**Comment by thestonefox** [comment]
GitHub issues are for reporting bugs, if you need help with general configuration then try the slack channel at http://invite.vrtk.io
