### ISSUE TITLE
Ability to set FloatRange min and max values

### ISSUE THREAD

**Issue by extendreality** [ExtendRealityLtd/Zinnia.Unity#505]
You can't set the min max values on a FloatRange property as the FloatRange is a strut. So just provide two methods on the FloatRange strut so its easier to update the values.

**Comment by thestonefox** [comment]
This is actually intended because the FloatRange strut is passed by value so direct modifications on the property would cause adverse effects. The recommended way is to save out the property to a local type, make the change and save back into it.
