### ISSUE TITLE
MinMaxRange property drawer randomly resets the input occasionally

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Zinnia.Unity#508]
### Environment

* Code source: GitHub
* Code version:  1.19.0
* Platform version: Unity 2014.3.14f1
* 3rd party dependencies:

### Steps to reproduce

* Add Empty GameObject to scene
* Create simple script implementing the MinMaxRange property drawer:

```
using Malimbe.PropertySerializationAttribute;
using UnityEngine;
using Zinnia.Data.Attribute;
using Zinnia.Data.Type;

public class MinMaxRange : MonoBehaviour
{
    [Serialized]
    [field: MinMaxRange(-1f, 1f)]
    public FloatRange Range { get; set; } = new FloatRange(-0.5f, 0.5f);
}
```

* Add script to Empty GameObject
* Make Empty GameObject a prefab

* Default settings should be: `-0.5` ~~ `0.5`
* Run the scene then stop the scene
* Change min range to `-0.2` (don't just change the `5` to a `2` delete the whole field and type `-0.2`
  * Prefab field should now go bold as this is a value change on the original prefab
* Run the scene then stop the scene
* Min range value should still be `-0.2`
* Change min range to `-0.5` (don't just change the `2` to a `5` delete the whole field and type `-0.5`
* Run the scene then stop the scene

* Min range has now reverted to `0`

### Expected behavior

Value to stay at `-0.5`

### Current behavior

Value resets to '0'

![badprop](https://user-images.githubusercontent.com/1029673/87154234-c5fdd200-c2b0-11ea-8212-ea496ac6b256.gif)

**Comment by thestonefox** [comment]
A fix for this seems to be setting the property to dirty if a change has occurred:

```
if (GUI.changed)
{
    EditorUtility.SetDirty(property.serializedObject.targetObject);
}
```

![fixedprop](https://user-images.githubusercontent.com/1029673/87155091-3fe28b00-c2b2-11ea-8747-49b0abdeb43e.gif)

**Comment by thestonefox** [comment]
@bddckr chip in if you can think of a better/more suitable way of fixing this odd one

**Comment by bddckr** [comment]
Is the fact that it's from a prefab the trigger for the bug? Or is it fine for non-prefab usage of that class, too?

If it's only with prefab stuff (even if just an instance of the prefab, instead of the prefab itself), then there might be some bug in the change handling (where do we do this? Is this related to our default change checker thing or is this literally just the class definition you pasted above on its own?)... What comes to mind is
* `UnityEditor.PrefabUtility.RecordPrefabInstancePropertyModifications`
* `serializedObject.ApplyModifiedProperties()` not being called perhaps.
* `ApplyModifiedProperties` being used but the change is not applied by going through the serialized object APIs of Unity.

**Comment by thestonefox** [comment]
only happens when the control is used within a prefab.

**Comment by thestonefox** [comment]
Tried this:

```
Undo.RecordObject(property.serializedObject.targetObject, property.displayName);
property.SetValue(new FloatRange(output));
property.serializedObject.ApplyModifiedProperties();
```

doesn't fix the issue


tried:

```
Undo.RecordObject(property.serializedObject.targetObject, property.displayName);
property.SetValue(new FloatRange(output));
PrefabUtility.RecordPrefabInstancePropertyModifications(property.serializedObject.targetObject);
```

and that does work.

so what is better, the above or the current fix, which is:

```
Undo.RecordObject(property.serializedObject.targetObject, property.displayName);
property.SetValue(new FloatRange(output));
if (GUI.changed)
{
    EditorUtility.SetDirty(property.serializedObject.targetObject);
}
```

**Comment by bddckr** [comment]
Going by [the docs for `SetDirty`](https://docs.unity3d.com/ScriptReference/EditorUtility.SetDirty.html) I'd say stay away from `SetDirty` if you can!

**Comment by thestonefox** [comment]
Unity seem to suggest using https://docs.unity3d.com/ScriptReference/PrefabUtility.RecordPrefabInstancePropertyModifications.html

after doing an `Undo.RecordObject` (like we do) so maybe that is the better choice (and it seems to work and undo works too)

**Comment by bddckr** [comment]
Hmm [the docs for `RecordPrefabInstancePropertyModifications`](https://docs.unity3d.com/ScriptReference/PrefabUtility.RecordPrefabInstancePropertyModifications.html) specifically say to instead work with `SerializedProperty` and `SerializedObject`.

That is normally what works, for all the needs (whether prefab or not). The only gotcha is having to call `ApplyModifiedProperties` at the end (and maybe a call to `Update` or `UpdateIfRequiredOrScript`). See the docs examples and big intro text: https://docs.unity3d.com/ScriptReference/SerializedObject.html

**Comment by thestonefox** [comment]
The only thing I can think is this is a bug within the Unity component. The MinMaxRange _is_ a Unity editor component and the way it breaks is not consistent at all.

**Comment by bddckr** [comment]
Can you reproduce this in a project that isn't pulling in our custom editor shenanigans via Malimbe etc.?

**Comment by thestonefox** [comment]
i can probably disable the custom editor stuff and try it

**Comment by thestonefox** [comment]
If i just delete the UnityIntegration DLL from the editor, that _should_ disable all that stuff anyway right?

**Comment by thestonefox** [comment]
If the above does what I think it does, then it's still broken. But let me try in a fresh project without any zinnia or malimbe

**Comment by bddckr** [comment]
You will probably have to restart Unity for it to unload the dll, too. But at that point it might restore the dll from the package.

But yes, if the dll is not used by Unity that should do it as that's where the stuff is coming from :)

🤞

**Comment by thestonefox** [comment]
Breaks outside of any Malimbe/Zinnia usage (only thing I'm still using is the Supyrb serialized property extensions.

**Comment by thestonefox** [comment]
We do actually use Supyrb for setting the value

**Comment by bddckr** [comment]
That probably doesn't go through and sets the values properly with the SerializedProperty API, does it? I remember there being a hole in Unity's API that was only resolved by using reflection (Supyrb does that IIRC), which of course does not set the value in any way Unity's serialization system would then see without some manual calls like those Undo recording etc.

At least I think this might be it.

**Comment by thestonefox** [comment]
Yeah, you can't set custom datatypes with the SerializedProperty stuff, only what they offer. So that Supyrb SetValue goes through the FieldInfo/PropertyInfo and sets the value.

So something in there is not doing the thing unity expects

**Comment by thestonefox** [comment]
Yeah if you use the MinMaxRange with a Vector2 then it works (as it does go through the serialized stuff)

**Comment by thestonefox** [comment]
So what's the solution here? just whack in the 

`PrefabUtility.RecordPrefabInstancePropertyModifications(property.serializedObject.targetObject);`?

**Comment by bddckr** [comment]
Well if it works and Unity still doesn't offer new API for that glaring hole there - go for that!

**Comment by thestonefox** [comment]
What about:

```
Undo.RecordObject(property.serializedObject.targetObject, property.displayName);
property.SetValue(new FloatRange(output));
if (property.isInstantiatedPrefab)
{
    PrefabUtility.RecordPrefabInstancePropertyModifications(property.serializedObject.targetObject);
}
```

i.e. only run it if it's a prefab, because it works fine if its not a prefab

**Comment by bddckr** [comment]
Does it really? Like you can hit undo just fine outside a prefab? Same for entering and exiting play mode with changes? Back when I had to deal with this there was a long list of details to get right, and the answer never was "you can just set the object's value (via reflection or directly) and Unity knows about it" - always had to get their serialization stuff to set it instead 😬

If it does that seems like a better idea. I can see `RecordPrefabInstancePropertyModifications` breaking in the future if it's used outside of a prefab. Would probably be marked as no breaking change by Unity.

With the `isInstantiatedPrefab` check, does it still work for changes on the prefab itself (i.e. not an instance of it)?

**Comment by thestonefox** [comment]
Ok here are my test results for the above proposed fix:

### Script

```
//On custom type
[MinMaxRange(-1f, 1f)]
public FloatRange range  = new FloatRange(-0.5f, 0.5f);

//On supported type
[MinMaxRange(-1f, 1f)]
public Vector2 rangeB = new Vector2(-0.5f, 0.5f);
```

(Running through original steps)

### Script attached to GameObject (no prefab)

Range: Changes fine and as expected
RangeB: Changes fine and as expected

### Script attached to Prefab

Range: Changes fine and as expected
RangeB: Changes fine and as expected

So it all seems fine to me

**Comment by thestonefox** [comment]
Oh also if you just edit the Prefab (not instance) then it just works like the Script Attached To GameObject anyway and still saves fine

**Comment by extendreality** [comment]
Fixed in https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/507
