### ISSUE TITLE
Transform Direction Extractor UseLocal result not expected

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Zinnia.Unity#514]
### Environment

* Code source: github
* Code version: 18d34c1

### Steps to reproduce

Goal: make a up-right camera following HeadsetAlias

1. Set up tilia xr environment (unityxr, tracked alias, etc)
2. Create a camera named "Record Camera"
3. Create a game object "Follow Position", add component "TransformPositionExtractor"
4. Drag HeadsetAlias into Source field, Extracted event calls `Record Camera.transform.position`. We want the Record Camera follow the **world space position, so turn off UseLocal.**
![image](https://user-images.githubusercontent.com/22952143/90421658-58816480-e0ec-11ea-89b2-64d787dd67b3.png)
5. Create a game object "Follow Rotation", add component "TransformDirectionExtractor"
6. Add the custom script AxesToRotation (see the Append). It takes two Vector3 axes and compute a Quaternion rotation.
7. Drag HeadsetAlias into Source field of direction extractor, Extracted event calls to AxesToRotation.Forward and AxesToRotation.EmitRotation(). We want the Record Camera's **world space forward direction, so turn off UseLocal.**
8. AxesToRotation rotation emitted event calls to `Record Camera.transform.rotation`. We want the upright orientation, so we use the ConstructFrom = Forward and Up vectors.
![image](https://user-images.githubusercontent.com/22952143/90424111-2a9e1f00-e0f0-11ea-9995-26eefe3324fa.png)
9. Add MomentProcess to both FollowPosition and FollowRotation, create a MomentProcessor to execute both of them.
![image](https://user-images.githubusercontent.com/22952143/90423320-d0508e80-e0ee-11ea-968f-4cd4b171d1b7.png)

### Current behavior

The Record Camera's position is followed correctly, but it is pointing in world space's z direction, not following the forward direction of HeadsetAlias.

For Transform Position Extractor, when UseLocal is off, it returns the source transform's **world space** position, while UseLocal is on, it returns the source transform's **local**Position
```
        protected override Vector3? ExtractValue()
        {
            ...
            return UseLocal ? Source.transform.localPosition : Source.transform.position;
```

However, the current Transform Direction Extractor, when UseLocal is off, it returns the Vector3.forward (which is independent of any source), while UseLocal is on, it returns the source transform's **world** space forward instead of **local** space forward
```
        protected override Vector3? ExtractValue()
        {
                ...
                case AxisDirection.Forward:
                    return UseLocal ? Source.transform.forward : Vector3.forward;
```

### Expected behavior

The transform direction extractor, when UseLocal is off should return the **source transform's world space** direction, and when UseLocal is on should return the **source transform's local space** direction .
i.e. `return UseLocal ? Source.transform.localRotation * Vector3.forward : Source.transform.forward;`

### Append

```
namespace VRToolkitExtras.Data.Type.Transformation
{
    using System;
    using Malimbe.PropertySerializationAttribute;
    using UnityEngine;
    using UnityEngine.Events;

    public class AxesToRotation : MonoBehaviour
    {
        [Serializable]
        public class QuaternionUnityEvent : UnityEvent<Quaternion>
        {
        }

        [Serialized]
        public Vector3 Forward { get; set; } = Vector3.forward;
        [Serialized]
        public Vector3 Up { get; set; } = Vector3.up;
        [Serialized]
        public Vector3 Right { get; set; } = Vector3.right;

        public enum ConstructFromType
        {
            ForwardAndUp,
            ForwardAndRight
        }
        [Serialized]
        public ConstructFromType ConstructFrom { get; set; } = ConstructFromType.ForwardAndUp;

        public Quaternion Rotation { get; private set; }

        public QuaternionUnityEvent RotationEmitted = new QuaternionUnityEvent();

        public void EmitRotation()
        {
            switch (ConstructFrom)
            {
                default:
                case ConstructFromType.ForwardAndUp:
                    {
                        Rotation = Quaternion.LookRotation(Forward, Up);
                        RotationEmitted?.Invoke(Rotation);
                    }
                    break;
                case ConstructFromType.ForwardAndRight:
                    {
                        Vector3 up = Vector3.Cross(Forward, Right);
                        Rotation = Quaternion.LookRotation(Forward, up);
                        RotationEmitted?.Invoke(Rotation);
                    }
                    break;
            }
        }
    }
}
```

**Comment by thestonefox** [comment]
this doesn't make sense.

Why should the direction extractor return localRotation and rotation?

**Comment by fight4dream** [comment]
sorry i hurried and confused myself, I meant to say local and world 'direction' instead of rotation.
i've editted the issue and provided steps.
Although I have to include a custom script. I hope it is easy enough to follow and the issue is pinpointed.
Let me know if you need more info. Thanks
