### ISSUE TITLE
BooleanAction can reset values & sources after reimporting the project

### ISSUE THREAD

**Issue by Auroriax** [ExtendRealityLtd/Zinnia.Unity#549]
### Environment

* Code source: Github
* Code version: 1.38.1
* Platform version: Unity 2020.3.16f1
* 3rd party dependencies: None

### Steps to reproduce

1) Create a fresh project, add Zinnia using the install instructions.
2) Add a BooleanAction to the default scene.
3) Save the scene, then reimport all the files in the project (easiest way to trigger this manually is to right click in the Project window and select "Reimport All").
4) The same scene should open. Select the BooleanAction. You should notice the component no longer has the "Default Value", "Initial Value" & "Sources" fields exposed: 
![image](https://user-images.githubusercontent.com/6784890/132315582-5acc13e6-4515-44a5-ad2a-fe81dfe3005e.png)
5) Put the scene into play mode. You should notice the values re-appearing on the BooleanAction, but with their default values (e.g. if you changed any of these values or added sources before the reimport, those values are lost).

Nothing is logged to the console. A workaround is to manually reload the scene into the editor: once the scene is reloaded, the values are visible in the inspector & have the correct settings.

### Expected behavior

After a reimport, Boolean Actions should still have the Initial Value, Default Value & Sources visible in the inspector, and have the values they were previously assigned in the scene, instead of returning to the default values.

### Current behavior

After a reimport, Initial Value, Default Value, and Sources disappear from the inspector, and once they return, they no longer have the values they were assigned until the scene is reloaded in the editor.

**Comment by thestonefox** [comment]
What happens if you close unity and reopen it? do the fields reappear?

If so then this is not an issue with Zinnia but a bug in Unity: 

https://issuetracker.unity3d.com/issues/unity-does-not-execute-code-weavers-when-its-opened-for-the-first-time

**Comment by Auroriax** [comment]
Can confirm that the fields re-appear when, after re-importing, Unity is closed and opened again.

Thank you for pointing me towards the relevant Unity issue! Seems I'll have to wait for Unity to fix this. I'll close this issue.
