### ISSUE TITLE
Restricted component field causes editor style change

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Zinnia.Unity#559]
### Environment

* Code version: 3d66d74
* Platform version: 2019.2.0f1

### Steps to reproduce

1. Inspect any component with the [Restricted] attribute
2. Click the dot besides any Restricted object field to bring up the reference chooser

### Expected behavior

The editor style should not be changed

### Current behavior

All other non-focused fields text color are changed to a very hard to see grey.

### PS
The original style is recovered when entering Play mode or restart unity

**Comment by thestonefox** [comment]
PR with fix https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/560
