### ISSUE TITLE
Artificial based directional controls

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Zinnia.Unity#60]

**Comment by thestonefox** [comment]
## WIP Concept:

* Use Interactable prefab that moves the object around using the transform follow
* Need a new component that clamps the (local?) x,y,z position of a GameObject
* After the transform follow moment is processed, this clamp process is run to keep the GameObject within the specified limits.
* Upon release the velocity from the controller is applied to the object and the release velocity can be controlled by the interactable rigidbody drag.
* Need some way of driving the object to the target value. Perhaps using the TransformPropertyApplier and it creates a TransformData object for the location and then just uses the transition time to move it back.

### Questions

What to call the TransformClamp?
Is it an extension of an existing type? Is it a type of mutator as it's mutating the position?
Although it needs to be an IProcessable, so maybe it's just easier being its own thing? and new Data.Operation called like `TransformPropertyRestrictor` which extends to be `TransformPositionRestrictor`?


Also, how does this work for a pushable button? It's possible to push the interactable with a collider, but to mimic the on touch push button down and back up should perhaps just be a manual collection of event calls on the collision notifier in the interactable?

**Comment by bddckr** [comment]
Done in https://github.com/thestonefox/VRTK/pull/1942.
